project_id = "waikgtdlwksjhxolwpyi"

[functions.process-daily-accruals]
verify_jwt = false

[functions.test-afas-connection]
verify_jwt = false

[functions.get-afas-schema]
verify_jwt = false

[functions.test-afas-read]
verify_jwt = false

[functions.test-afas-write]
verify_jwt = false

[functions.test-afas-draws]
verify_jwt = false

[functions.get-afas-debtors]
verify_jwt = false

[functions.post-period-to-afas]
verify_jwt = false

[functions.correct-event-amount]
verify_jwt = false

[functions.parse-loan-document]
verify_jwt = false
